export const ADD_MOVIE = "ADD_MOVIE";
export const DELETE_MOVIE = "DELETE_MOVIE";
export const EDIT_MOVIE = "EDIT_MOVIE";
export const SEARCH_MOVIE_NAME = "SEARCH_MOVIE_NAME";
export const SEARCH_MOVIE_RATE = "SEARCH_MOVIE_RATE";
